version: '3.7'

services:

  lawira-backend:
    container_name: lawira-backend
    build:
      context: backend
    restart: always
    image: api-backend:dev
    ports:
      - "8080:8080"
    depends_on:
      - lawira-db

  lawira-db:
    image: mariadb:10.2
    container_name: lawira-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3307:3306'
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    restart: on-failure
    volumes:
      - lawira-db-vol:/var/lib/mysql

volumes:
  lawira-db-vol:

networks:
  default:
    external:
      name: app-network
