version: '3.7'

services:

  backend:
    container_name: api-backend
    build:
      context: backend
    restart: always
    image: api-backend:dev
    ports:
      - "10080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - '10000:5432'
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_PORT: 5432
    volumes:
      - postgres-db-vol:/var/lib/postgres/data

  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  postgres-db-vol:
  maria-db-vol:
  my-db:

networks:
  default:
    external:
      name: app-network
