spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/postgres-db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog-master.xml

jwt:
  secret: "This is a secret"
