spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: db/changelog-master.xml

jwt:
  secret: "This is a secret"
