spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect


jwt:
  secret: "This is a secret"
