spring:
  datasource:
    url: jdbc:mysql://lawira-db:3306/db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
  liquibase:
    change-log: db/changelog-master.xml

jwt:
  secret: "This is a secret"
